  version: "3.8"
  services:
    web:
      build: .
      ports:
        - "8000:8000"
      command: poetry run python src/manage.py runserver 0.0.0.0:8000


      depends_on:
        - db
        - redis

    db:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"


    poetry:
      build: .
      command: poetry install
      volumes:
        - .:/app

    redis:
      image: redis:latest
      ports:
        - "6379:6379"

  volumes:
    postgres_data:
