# Generated by Django 4.2.7 on 2023-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("client", "CLIENT"), ("admin", "ADMIN"), ("employee", "EMPLOYEE")],
                max_length=10,
            ),
        ),
    ]
