# Generated by Django 4.2.6 on 2023-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("client", "CLIENT"), ("admin", "ADMIN"), ("employee", "EMPLOYEE")],
                max_length=10,
            ),
        ),
    ]
