# Generated by Django 4.2.6 on 2023-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_invitation_inviter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Client", "CLIENT"), ("Admin", "ADMIN"), ("Employee", "EMPLOYEE")],
                default="Client",
                max_length=10,
            ),
        ),
    ]
