# Generated by Django 4.2.6 on 2023-11-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_google_auth",
            field=models.BooleanField(default=False),
        ),
    ]
