# Generated by Django 4.2.7 on 2023-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                through="products.ProductItem",
                to="products.product",
                verbose_name="Products",
            ),
        ),
    ]
