name: Basic deploy

on:
  push:
    branches: [develop]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: eu-north-1
          aws_elb_app_port: 8000
          tf_state_bucket: dsjh-2
          aws_ec2_instance_type: t3.small
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo apt-get install -y docker-compose
          cd logistic-service && sudo docker-compose build && sudo docker-compose up --detach
