name: tests
run-name: ${{ github.actor }} check
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest poetry pre-commit
      - name: Run Unit Tests
        run: |
          pytest || echo "No tests found, skipping..."
      - name: Run Pre-commit Hooks
        run: |
          poetry run pre-commit run --all-files
